apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    user: griduser
    secureJsonData:
      password: gridpass
    jsonData:
      database: gridbot
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    editable: true
    version: 1
